/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusRouteImport } from './routes/bonus'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as PlayDetectiveRouteImport } from './routes/play.detective'
import { Route as PlayMazeRouteImport } from './routes/play.maze'
import { Route as PlayMemoryRouteImport } from './routes/play.memory'
import { Route as PlayOrientationRouteImport } from './routes/play.orientation'
import { Route as PlaySequencingRouteImport } from './routes/play.sequencing'
import { Route as PlaySimonRouteImport } from './routes/play.simon'
import { Route as PlaySpotRouteImport } from './routes/play.spot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRoute = BonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDetectiveRoute = PlayDetectiveRouteImport.update({
  id: '/play/detective',
  path: '/play/detective',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMazeRoute = PlayMazeRouteImport.update({
  id: '/play/maze',
  path: '/play/maze',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMemoryRoute = PlayMemoryRouteImport.update({
  id: '/play/memory',
  path: '/play/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOrientationRoute = PlayOrientationRouteImport.update({
  id: '/play/orientation',
  path: '/play/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySequencingRoute = PlaySequencingRouteImport.update({
  id: '/play/sequencing',
  path: '/play/sequencing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySimonRoute = PlaySimonRouteImport.update({
  id: '/play/simon',
  path: '/play/simon',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySpotRoute = PlaySpotRouteImport.update({
  id: '/play/spot',
  path: '/play/spot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/caregiver': typeof CaregiverRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/parent': typeof ParentRoute
  '/reminders': typeof RemindersRoute
  '/play/detective': typeof PlayDetectiveRoute
  '/play/maze': typeof PlayMazeRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/orientation': typeof PlayOrientationRoute
  '/play/sequencing': typeof PlaySequencingRoute
  '/play/simon': typeof PlaySimonRoute
  '/play/spot': typeof PlaySpotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/caregiver': typeof CaregiverRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/parent': typeof ParentRoute
  '/reminders': typeof RemindersRoute
  '/play/detective': typeof PlayDetectiveRoute
  '/play/maze': typeof PlayMazeRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/orientation': typeof PlayOrientationRoute
  '/play/sequencing': typeof PlaySequencingRoute
  '/play/simon': typeof PlaySimonRoute
  '/play/spot': typeof PlaySpotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/caregiver': typeof CaregiverRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/parent': typeof ParentRoute
  '/reminders': typeof RemindersRoute
  '/play/detective': typeof PlayDetectiveRoute
  '/play/maze': typeof PlayMazeRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/orientation': typeof PlayOrientationRoute
  '/play/sequencing': typeof PlaySequencingRoute
  '/play/simon': typeof PlaySimonRoute
  '/play/spot': typeof PlaySpotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus'
    | '/caregiver'
    | '/dashboard'
    | '/login'
    | '/memories'
    | '/parent'
    | '/reminders'
    | '/play/detective'
    | '/play/maze'
    | '/play/memory'
    | '/play/orientation'
    | '/play/sequencing'
    | '/play/simon'
    | '/play/spot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonus'
    | '/caregiver'
    | '/dashboard'
    | '/login'
    | '/memories'
    | '/parent'
    | '/reminders'
    | '/play/detective'
    | '/play/maze'
    | '/play/memory'
    | '/play/orientation'
    | '/play/sequencing'
    | '/play/simon'
    | '/play/spot'
  id:
    | '__root__'
    | '/'
    | '/bonus'
    | '/caregiver'
    | '/dashboard'
    | '/login'
    | '/memories'
    | '/parent'
    | '/reminders'
    | '/play/detective'
    | '/play/maze'
    | '/play/memory'
    | '/play/orientation'
    | '/play/sequencing'
    | '/play/simon'
    | '/play/spot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusRoute: typeof BonusRoute
  CaregiverRoute: typeof CaregiverRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRoute
  ParentRoute: typeof ParentRoute
  RemindersRoute: typeof RemindersRoute
  PlayDetectiveRoute: typeof PlayDetectiveRoute
  PlayMazeRoute: typeof PlayMazeRoute
  PlayMemoryRoute: typeof PlayMemoryRoute
  PlayOrientationRoute: typeof PlayOrientationRoute
  PlaySequencingRoute: typeof PlaySequencingRoute
  PlaySimonRoute: typeof PlaySimonRoute
  PlaySpotRoute: typeof PlaySpotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/detective': {
      id: '/play/detective'
      path: '/play/detective'
      fullPath: '/play/detective'
      preLoaderRoute: typeof PlayDetectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/maze': {
      id: '/play/maze'
      path: '/play/maze'
      fullPath: '/play/maze'
      preLoaderRoute: typeof PlayMazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/memory': {
      id: '/play/memory'
      path: '/play/memory'
      fullPath: '/play/memory'
      preLoaderRoute: typeof PlayMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/orientation': {
      id: '/play/orientation'
      path: '/play/orientation'
      fullPath: '/play/orientation'
      preLoaderRoute: typeof PlayOrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/sequencing': {
      id: '/play/sequencing'
      path: '/play/sequencing'
      fullPath: '/play/sequencing'
      preLoaderRoute: typeof PlaySequencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/simon': {
      id: '/play/simon'
      path: '/play/simon'
      fullPath: '/play/simon'
      preLoaderRoute: typeof PlaySimonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/spot': {
      id: '/play/spot'
      path: '/play/spot'
      fullPath: '/play/spot'
      preLoaderRoute: typeof PlaySpotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusRoute: BonusRoute,
  CaregiverRoute: CaregiverRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRoute,
  ParentRoute: ParentRoute,
  RemindersRoute: RemindersRoute,
  PlayDetectiveRoute: PlayDetectiveRoute,
  PlayMazeRoute: PlayMazeRoute,
  PlayMemoryRoute: PlayMemoryRoute,
  PlayOrientationRoute: PlayOrientationRoute,
  PlaySequencingRoute: PlaySequencingRoute,
  PlaySimonRoute: PlaySimonRoute,
  PlaySpotRoute: PlaySpotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
